### ISSUE TITLE
OpenWebPage Action Link

### ISSUE THREAD

**Issue by alireza8n** [divar-ir/kenar-docs#32]
I noticed a small issue in the YAML code snippet provided below:
```yaml
"action": {
    "type": "OPEN_WEB_PAGE",
    "fallback_link": "https://your.website.com",
    "payload": {
        "@type": "type.googleapis.com/widgets.OpenWebPagePayload",
        "url": "https://your.website.com"
    }
}
```
Correct "url" to "link" in YAML code
